[package]
name = "agenda-yaml"
version = "0.1.0"
entrypoint = "agenda.typ"
authors = ["baptiste <https://github.com/baptiste>"]
license = "MPL-2.0"
description = "A tabular template for meeting agendas with agenda items defined in Yaml."

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
